# Generated by Django 3.0.1 on 2020-01-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('hint', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='scavengerhunt',
            name='clues',
            field=models.ManyToManyField(to='scavenger.Clue'),
        ),
    ]
