# Generated by Django 3.0.1 on 2020-01-15 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0004_auto_20200114_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_phone_number', models.CharField(blank=True, max_length=100)),
                ('which_clue', models.IntegerField(default=0)),
                ('scavenger_hunt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scavenger.ScavengerHunt')),
            ],
        ),
    ]
