# Generated by Django 3.0.1 on 2020-01-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0005_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scavengerhunt',
            name='players_phone_number',
        ),
    ]
